config/routes.rb
Rails.application.routes.draw do
  # TO DO set the heroku url below
  default_url_options :host => 'http://tamuber123.herokuapp.com/'
  get 'password_resets/new'
  get 'password_resets/edit'
  root   'static_pages#home'
  
  get 'password_resets/new'
  get '/edit',    to: 'users#edit'
  get    '/help',    to: 'static_pages#help'
  get    '/checklist',    to: 'static_pages#checklist'
  post   '/checklist',    to: 'test#create'
  get    '/about',   to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/try',   to: 'static_pages#try'
  post '/call', to: 'twilio#call', as: 'call'
  post '/connect/:sales_number', to: 'twilio#connect', as: 'connect'
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    The TamUber Application
    by ActiveVolcano
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path%></li>
    </ul>
  </nav>
</footer>

app/views/shared/_header.html.erb
<!--<header class="navbar navbar-fixed-top navbar-inverse">-->
<!--  <div class="container">-->
  <!--<%= link_to "TamUber Driver Safety Interface", root_path, id: "logo" %>-->
  <!--<%= link_to_if(logged_in?, "TamUber Driver Safety Interface", current_user, id: "logo") {link_to("TamUber Driver Safety Interface", root_path, id: "logo")} %>-->
         
<!--    <nav>-->
<!--      <ul class="nav navbar-nav navbar-right">-->
<!--        <% if logged_in? %>-->
        
<!--          <li><%= link_to "Home", current_user %></li>-->
          <!--<li><%= link_to "Profile", edit_path %></li>-->
<!--          <li><%= link_to "Profile", edit_user_path(current_user) %></li>-->
<!--          <li><%= link_to "Log out", logout_path, method: :delete %></li>-->
         
          <!--<li><%= link_to "Users", '#' %></li>-->
          <!--<li class="dropdown">-->
          <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
          <!--    Account <b class="caret"></b>-->
          <!--  </a>-->
          <!--  <ul class="dropdown-menu">-->
              <!--<li><%= link_to "Profile", current_user %></li>-->
          <!--    <li class="divider"></li>-->
          <!--    <li>-->
          <!--      <%= link_to "Log out", logout_path, method: :delete %>-->
          <!--    </li>-->
          <!--  </ul>-->
          <!--</li>-->
<!--        <% else %>-->
<!--          <li><%= link_to "Home", root_path %></li>-->
<!--          <li><%= link_to "Log in", login_path %></li>-->
<!--        <% end %>-->
<!--        <li><%= link_to "Help", help_path %></li>-->
<!--      </ul>-->
<!--    </nav>-->
<!--  </div>-->
<!--</header>-->






<header class="navbar navbar-fixed-top navbar-inverse">
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <div class="container">
  <!--<%= link_to "TamUber Driver Safety Interface", root_path, id: "logo" %>-->
  <!--<%= link_to_if(logged_in?, "TamUber Driver Safety Interface", current_user, id: "logo") {link_to("TamUber Driver Safety Interface", root_path, id: "logo")} %>-->
  
  <style>
    #menu {
      color: white;
    }
  </style>
    <div class="navbanr-header">
          <button type="button" id = "menu" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav-demo" aria-expanded="false">
            Menu
            <span class="sr-only">Toggle navigation</span>
            <!--<span class="icon-bar"></span>-->
            <!--<span class="icon-bar"></span>-->
            <!--<span class="icon-bar"></span>-->
          </button>
          <%= link_to_if(logged_in?, "TamUber Driver Safety Interface", current_user, id: "logo") {link_to("TamUber Driver Safety Interface", root_path, id: "logo")} %>
          <!--<a href="#" class="navbar-brand"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> IMGS</a>-->
    </div>
    
    
    
    
    <nav>
    <div class="collapse navbar-collapse" id="bs-nav-demo">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        
          <li><%= link_to "Home", current_user %></li>
          <!--<li><%= link_to "Profile", edit_path %></li>-->
          <li><%= link_to "Profile", edit_user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
         
          <!--<li><%= link_to "Users", '#' %></li>-->
          <!--<li class="dropdown">-->
          <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
          <!--    Account <b class="caret"></b>-->
          <!--  </a>-->
          <!--  <ul class="dropdown-menu">-->
              <!--<li><%= link_to "Profile", current_user %></li>-->
          <!--    <li class="divider"></li>-->
          <!--    <li>-->
          <!--      <%= link_to "Log out", logout_path, method: :delete %>-->
          <!--    </li>-->
          <!--  </ul>-->
          <!--</li>-->
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><%= link_to "Help", help_path %></li>
      </ul>
      <!--</div>-->
    </div>
    </nav>
  </div>
</header>

app/views/shared/_header2.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "TamUber Driver Safety Interface", root_path, id: "logo" %>
         
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <!--<li><%= link_to "Home", root_path %></li>-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", login_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->